```{r results='show'}
data1 <- read.csv(file = 'Telecom Data.csv')
str(data1)
head(data1)
```

```{r results='show'}
#Use 70% of dataset as training set and remaining 30% as testing set
sample <- sample(c(TRUE, FALSE), nrow(data1), replace=TRUE, prob=c(0.7,0.3))
train  <- data1[sample, ]
test   <- data1[!sample, ]

#view dimensions of training set
dim(train)


#view dimensions of test set
dim(test)
```
```{r results="show"}
prop.table(table(test$Churn))

```
```{r results="show"}
prop.table(table(train$Churn))

```
```{r results="show"}
library(DAAG)
library(party)
library(rpart)
library(rpart.plot)
library(mlbench)
library(caret)
library(pROC)
library(tree)
```

```{r results="show"}
# Predict churn based on NonUSTravel_Yes
tree_1 <- ctree(as.factor(Churn) ~ MonthlyMinutes,        
                     data = train)        # Using the training data

plot(tree_1)
```
```{r results="show"}
 tree_2 <- ctree(as.factor(Churn)~ChildrenInHH+Homeownership+MonthlyMinutes+MonthlyRevenue+TotalRecurringCharge+DirectorAssistedCalls+OverageMinutes+RoamingCalls+DroppedCalls+UnansweredCalls+CustomerCareCalls+MonthsInService+UniqueSubs+ActiveSubs+CurrentEquipmentDays+
                   as.factor(PrizmCode+AgeHH1+AgeHH2), data=train)
```
