
---
title: "Telecom Churn Prediction EDA"
author: "Sunisha Harish"
date: "`r Sys.Date()`"
# date: "`r Sys.Date()`"
output:
  html_document:
    code_folding: hide
    number_sections: false
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r, echo=T, results=T}
telecom <- data.frame(read.csv("Telecom Data.csv"))
str(telecom)
head(telecom)
```


```{r, echo=T, results=T}
library(ggplot2)
ggplot(telecom, aes(y=CreditRating)) + geom_boxplot( colour="orange", fill="black") + ggtitle("Credit  using `ggplot`")
```
```{r, echo=T, results=T}
Churned <- subset(telecom, Churn=="Yes")
NotChurned <- subset(telecom, Churn=="No")
str(Churned)
str(NotChurned)
```

```{r, echo=T, results=T}
library(ggplot2)
ggplot(Churned, aes(x = CreditRating)) + geom_bar(col="black", fill="green") + ggtitle("Credit Rating for Churned Telecom Data") + labs(x="Credit Rating (x-axis) ", y=" Count (y-axis)"+ ylim(0,100))
```

```{r, echo=T, results=T}
library(ggplot2)
ggplot(NotChurned, aes(x = CreditRating)) + geom_bar(col="black", fill="red") + ggtitle("Credit Rating for Not Churned Telecom Data") +  labs(x="Credit Rating (x-axis) ", y=" Count (y-axis)"+ ylim(0,1000))
```


```{r,results=T}
library(ezids)
#Creating a dataframe
Telecom_Data=data.frame(read.csv("Telecom Data.csv"))
str(Telecom_Data)

#Changing data type of occupation and churn into factor
Telecom_Data$Churn <- as.factor(Telecom_Data$Churn)
Telecom_Data$Occupation <- as.factor(Telecom_Data$Occupation)

#Printing the structure and summary of data
str(Telecom_Data)
summary(Telecom_Data)
```


```{r,results=T}
#Subsetting Churned and Retained data
Churned <- subset(Telecom_Data, Churn=="Yes")
Retained <- subset(Telecom_Data, Churn=="No")
```


```{r,results=T}
# Histogram for relationship between months in service and Churn

library(ggplot2)

ggplot(Churned, aes(x=MonthsInService, fill=Churn)) + geom_histogram(position='identity',alpha=0.6,color='aquamarine4',fill='aquamarine3')+xlab("Service period for churned customers (In Months) ")+ylab("Frequency") + theme_classic()+ggtitle("Service Months Distribution for Churned customers")

Mean_1=mean(Churned$MonthsInService)
Mean_1

Median_1=median(Churned$MonthsInService)
Median_1


# Barplot for Prizm Code effect on Churn
ggplot(Telecom_Data, aes(x=PrizmCode, fill = Churn)) +geom_bar(position = "dodge2")+ggtitle("Churn distribution for Prizm code")

#install.packages("plotly")
library(plotly)
colors <- c('rgb(128,133,133)', 'rgb(144,103,167)', 'rgb(171,104,87)', 'rgb(114,147,203)')


fig <- plot_ly(type='pie', labels=Churned$PrizmCode, values=Churned$n,
               textinfo='label+percent',
               insidetextorientation='radial',marker = list(colors = "Set1"),
                      line = list(color = '#FFFFFF', width = 1))
fig

fig_1 <- plot_ly(type='pie', labels=Retained$PrizmCode, values=Retained$n,
               textinfo='label+percent',
               insidetextorientation='radial',marker = list(colors = "Set1"),
                      line = list(color = '#FFFFFF', width = 1))
fig_1

```

```{r,results=T}

#Frequency distribution of Occupation

ggplot(Telecom_Data,aes(x=Occupation)) + geom_bar(fill = "bisque") + ggtitle("Frequency distribution of occupation") 

#Creating a contingency table for Occupation and Churn
Occupation_Churn<-table(Telecom_Data$Occupation,Telecom_Data$Churn)
str(Occupation_Churn)

#Performing Chi Square Test to check if occupation is independent of churn

chisq_test=chisq.test(Occupation_Churn)
chisq_test
p_value=chisq_test$p.value
p_value
```

Occupation is independent of churn.


