---
# This is the YAML header/metadata for the document
title: "Customer Churn Analysis code & Technical Analysis"
author: "Pranav Chandaliya"

output:
  html_document:
    code_folding: hide
    number_sections: true
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=F}
# The package "ezids" (EZ Intro to Data Science) includes a lot of the helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
# Once installed, load the library.
library(ezids)

```


```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
# knitr::opts_chunk$set(include = F)
# knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```


Loading our dataset into a dataframe.

```{r,results="show"}
Telecom_Data <- data.frame(read.csv("Telecom Data.csv"))
ncol(Telecom_Data)
nrow(Telecom_Data)
```

There are total 58 Columns and 51,047 Rows.

Let us print the structure of our data.

```{r,results=T}
str(Telecom_Data)
```

Here we are converting a few columns to factor data type.

```{r,results="show"}
#Telecom_Data$Churn <- factor(Telecom_Data$Churn)
#Telecom_Data$CreditRating <- factor(Telecom_Data$CreditRating) 
Telecom_Data$Occupation <- factor(Telecom_Data$Occupation)

```

```{r,results="show"}

library(ggplot2)
ggplot(Telecom_Data, aes(x = AgeHH1)) + 
  geom_histogram(aes(y = ..density..),
                 colour = 1, fill = "cyan")


ggplot(Telecom_Data, aes(x = AgeHH2)) + 
  geom_histogram(aes(y = ..density..),
                 colour = 1, fill = "cyan")

Telecom_Data$AgeHH1<-replace(Telecom_Data$AgeHH1,Telecom_Data$AgeHH1 <1 ,NA)
Telecom_Data$AgeHH2<-replace(Telecom_Data$AgeHH2,Telecom_Data$AgeHH2 <1 ,NA)
Telecom_Data$AgeHH1[is.na(Telecom_Data$AgeHH1)]<- median(Telecom_Data$AgeHH1,na.rm = TRUE)

Telecom_Data$AgeHH2[is.na(Telecom_Data$AgeHH2)]<- median(Telecom_Data$AgeHH2,na.rm = TRUE)

library(ggplot2)
ggplot(Telecom_Data, aes(x = AgeHH1)) + 
  geom_histogram(aes(y = ..density..),
                 colour = 1, fill = "cyan")
```
```{r age boxplot, echo=FALSE}
ggplot(Telecom_Data, aes(x = AgeHH1)) + 
  geom_boxplot(color="red", fill="green", alpha=0.2)


ggplot(Telecom_Data, aes(x = AgeHH2)) + 
  geom_histogram(aes(y = ..density..),
                 colour = 1, fill = "cyan")
```
```{r,results="show"}

ggplot(Telecom_Data, aes(x = DirectorAssistedCalls)) + 
  geom_histogram(color="red", fill="green", alpha=0.2)


```

```{r,results="show"}
ggplot(Telecom_Data, aes(x = MonthlyRevenue)) + 
  geom_boxplot(color="red", fill="green", alpha=0.2)

```

```{r,results="show"}
## checking inactive customers 

library(plotly)
fig <- plot_ly(y = Telecom_Data$MonthlyMinutes, type = "box", quartilemethod="linear") # or "inclusive", or "linear" by default

fig


nrow(subset(Telecom_Data, MonthlyRevenue <= 0))



## checking inactive customers 
nrow(subset(Telecom_Data, MonthlyMinutes <= 0))



#starwars %>% filter(mass > mean(mass, na.rm = TRUE))

```
```{r,results="show"}

Telecom_Data<-subset(Telecom_Data, MonthlyRevenue >  0)

Telecom_Data <-subset(Telecom_Data, MonthlyMinutes > 0)

library(plotly)
fig <- plot_ly(y = Telecom_Data$MonthlyMinutes, type = "box", quartilemethod="exclusive") # or "inclusive", or "linear" by default

fig

nrow(Telecom_Data)



```
```{r,results="show"}
#sum(is.na(Telecom_Data))
library(tidyverse)
map(Telecom_Data, ~sum(is.na(.)))

```

```{r,results="show"}
## Remvoing null values 

Telecom_Data <- na.omit(Telecom_Data) # Method 1 - Remove NA

sum(is.na(Telecom_Data))

```



```{r,results="show"}
library("dplyr")

table(Telecom_Data$Churn)

```
```{r,results="show"}

Telecom_Data_rm <- subset(Telecom_Data, select = -c(CustomerID ))

Telecom_Data_rm$Churn<-replace(Telecom_Data_rm$Churn, Telecom_Data_rm$Churn == "No", 0)

Telecom_Data_rm$Churn<-replace(Telecom_Data_rm$Churn, Telecom_Data_rm$Churn == "Yes", 1)

Telecom_Data_rm$Churn =as.numeric(Telecom_Data_rm$Churn )


#Telecom_Data_rm$CreditRating[Telecom_Data_rm$CreditRating == '1-Highest'] <- "1"


Telecom_Data_rm$CreditRating<-replace(Telecom_Data_rm$CreditRating, Telecom_Data_rm$CreditRating == "1-Highest", 1)

Telecom_Data_rm$CreditRating<-replace(Telecom_Data_rm$CreditRating, Telecom_Data_rm$CreditRating == "2-High", 2)

Telecom_Data_rm$CreditRating<-replace(Telecom_Data_rm$CreditRating, Telecom_Data_rm$CreditRating == "3-Good", 3)

Telecom_Data_rm$CreditRating<-replace(Telecom_Data_rm$CreditRating, Telecom_Data_rm$CreditRating == "4-Medium",4 )

Telecom_Data_rm$CreditRating<-replace(Telecom_Data_rm$CreditRating, Telecom_Data_rm$CreditRating == "5-Low", 5)

Telecom_Data_rm$CreditRating<-replace(Telecom_Data_rm$CreditRating, Telecom_Data_rm$CreditRating == "6-VeryLow", 6)

Telecom_Data_rm$CreditRating<-replace(Telecom_Data_rm$CreditRating, Telecom_Data_rm$CreditRating == "7-Lowest", 7)

Telecom_Data_rm$CreditRating <- as.numeric(Telecom_Data_rm$CreditRating )

#Telecom_Data_rm["Churn"][Telecom_Data_rm["Churn"] == "No" ] <- 0
#Telecom_Data_rm["Churn"][Telecom_Data_rm["Churn"] == "Yes" ] <- 1
#Telecom_Data_rm$Churn =as.numeric(Telecom_Data_rm$Churn )

unique(Telecom_Data_rm$CreditRating )


#sum(Telecom_Data_rm$CreditRating)
#sum(Telecom_Data_rm$Churn)
```

```{r,results="show"}

## Removing Features which have chi square value more than 0.05 and anova for numerical features 


select_feats = c("IncomeGroup","ChildrenInHH","Homeownership","PrizmCode","MonthlyMinutes", "MonthlyRevenue","TotalRecurringCharge","DirectorAssistedCalls","OverageMinutes","RoamingCalls","DroppedCalls","UnansweredCalls","CustomerCareCalls","MonthsInService","UniqueSubs","ActiveSubs","CurrentEquipmentDays","AgeHH1","AgeHH2","Churn")


Telecom_Data_rm <- subset(Telecom_Data_rm, select =select_feats)





```

```{r,results="show"}



```

```{r,results="show"}
# Install the required package
#install.packages("fastDummies")
cat_cols <-c("IncomeGroup","ChildrenInHH","Homeownership","PrizmCode")

# Load the library
library(fastDummies)
prepro_data<-dummy_cols(Telecom_Data_rm,select_columns=cat_cols,remove_first_dummy = TRUE,remove_selected_columns=TRUE)  







```

```{r,results="show"}


write.csv(prepro_data, "D:\\ID_Project\\T9-Outlier-22FA\\Data Preprocessing\\prepro_telcom_data.csv", row.names=FALSE)


``` 

```{r,results="show"}

#library(caret)

#x <-subset(Telecom_Data_rm,select = c(Churn))
#y<-subset(Telecom_Data_rm,select = -c(Churn))

churn_0 <- subset(prepro_data, prepro_data$Churn==0)
churn_1 <- subset(prepro_data, prepro_data$Churn==1)

nrow(churn_0)
nrow(churn_1)

set.seed(704)

churn_0_sampled = churn_0[ sample(nrow(churn_0),14711), ]

nrow(churn_0_sampled)
nrow(churn_1)

under_sampl= union(churn_0_sampled,churn_1)

library(caTools)


#make this example reproducible
set.seed(1)

#Use 80% of dataset as training set and remaining 20% as testing set
sample_under <- sample.split(under_sampl$Churn, SplitRatio = 0.8)
train_under  <- subset(under_sampl, sample_under == TRUE)
test_under   <- subset(under_sampl, sample_under == FALSE)

#view dimensions of training set
dim(train_under)
dim(test_under)

table(train_under$Churn)
table(test_under$Churn)

```
```{r,results="show"}


write.csv(train_under, "D:\\ID_Project\\T9-Outlier-22FA\\Data Preprocessing\\train_under.csv", row.names=FALSE)

write.csv(test_under, "D:\\ID_Project\\T9-Outlier-22FA\\Data Preprocessing\\test_under.csv", row.names=FALSE)

```



```{r,results="show"}
#install.packages("caTools")
library(caTools)


#make this example reproducible
set.seed(1)

#Use 80% of dataset as training set and remaining 20% as testing set
sample <- sample.split(prepro_data$Churn, SplitRatio = 0.8)
train  <- subset(prepro_data, sample == TRUE)
test   <- subset(prepro_data, sample == FALSE)

#view dimensions of training set
dim(train)
dim(test)

table(train$Churn)
table(test$Churn)


```



```{r, results='markup'}
library(smotefamily)
x<-subset(train, select = -c(Churn))
y<-train$Churn
#smote = SMOTE(x,y)
#x<-as.numeric(x)
#y<-as.numeric(y)
smote = SMOTE(x, y,6)
train_smote = smote$data
str(train_smote)

train_smote
write.csv(train_smote, "D:\\ID_Project\\T9-Outlier-22FA\\Data Preprocessing\\train_smote.csv", row.names=FALSE)

write.csv(test, "D:\\ID_Project\\T9-Outlier-22FA\\Data Preprocessing\\test.csv", row.names=FALSE)

```


