---
title: "Modelling_Vaish"
output: html_document
date: "2022-12-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ezids)
```


## R Markdown

```{r results='show'}
data <- read.csv(file = 'prepro_telcom_data.csv')
str(data)
head(data)
```

#Data partition
```{r results='show'}
#Use 70% of dataset as training set and remaining 30% as testing set
sample <- sample(c(TRUE, FALSE), nrow(data), replace=TRUE, prob=c(0.7,0.3))
#train  <- data[sample, ]
#test   <- data[!sample, ]

train <- read.csv(file = 'C:\\Users\\Vaishnavi\\OneDrive\\Desktop\\into to data science project\\T9-Outlier-22FA\\Data Preprocessing\\train_smote.csv')
test <- read.csv(file = 'C:\\Users\\Vaishnavi\\OneDrive\\Desktop\\into to data science project\\T9-Outlier-22FA\\Data Preprocessing\\test.csv')

#view dimensions of training set
dim(train)


#view dimensions of test set
dim(test)
```

#loading neccessary libraries
```{r results='show'}
library(naivebayes)
library(dplyr)
library(ggplot2)
library(psych)
```

```{r results='show'}
x = train[,-9]
y = train$Churn
```

# Model Building Naive Bayes Classification

```{r results='show'}
train$Churn = factor(train$class)
model <- naive_bayes(Churn ~ ., data = train, usekernel = T) 
summary(model)
```

#AUC and ROC Analysis

```{r results='show'}
library(pROC)


prediction <- predict(model, test, type="prob")

roc_object <- roc( test$Churn, prediction[,2])

auc( roc_object )


prediction_train <- predict(model, train, type="prob")

roc_object_train <- roc( train$Churn, prediction_train[,2])

auc( roc_object_train )


```


