---
# This is the YAML header/metadata for the document
title: "Customer Churn Analysis"
author: "Pranav Chandaliya"

output:
  html_document:
    code_folding: hide
    number_sections: true
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r init, include=F}
# The package "ezids" (EZ Intro to Data Science) includes a lot of the helper functions we developed for the course. 
# Some of the frequently used functions are loadPkg(), xkabledply(), xkablesummary(), uzscale(), etc.
# Once installed, load the library.
library(ezids)
```


```{r setup, include=FALSE}
# some of common options (and the defaults) are: 
# include=T, eval=T, echo=T, results='hide'/'asis'/'markup',..., collapse=F, warning=T, message=T, error=T, cache=T, fig.width=6, fig.height=4, fig.dim=c(6,4) #inches, fig.align='left'/'center','right', 
# knitr::opts_chunk$set(warning = F, results = "markup", message = F)
knitr::opts_chunk$set(warning = F, results = "hide", message = F)
# knitr::opts_chunk$set(include = F)
# knitr::opts_chunk$set(echo = TRUE)
options(scientific=T, digits = 3) 
# options(scipen=9, digits = 3) 
# ‘scipen’: integer. A penalty to be applied when deciding to print numeric values in fixed or exponential notation.  Positive values bias towards fixed and negative towards scientific notation: fixed notation will be preferred unless it is more than ‘scipen’ digits wider.
# use scipen=999 to prevent scientific notation at all times
```



```{r,results="show"}
telcm <- data.frame(read.csv("Telecom Data.csv"))
ncol(telcm)
nrow(telcm)
```


```{r,results="show"}
library(dplyr)
library(tidyr)

#summary(telcm)
#is.null(telcm)
null_values<-sapply(telcm, function(x) sum(is.na(x)))

```

```{r,results="show"}


##devtools::install_github('thomasp85/gganimate',force=T
                         )

#null_values

```
```{r,results="show"}
#install.packages("naniar")
library(naniar)
#vis_miss(telcm,warn_large_data = FALSE)
#gg_miss_fct(x = riskfactors, fct = marital)

```


```{r,results="show"}
#library
chrun_counts<- dplyr::count(telcm,Churn , sort = TRUE)
#pie(chrun_counts$n, labels = chrun_counts$Churn,explode = 0.1, main = "Pie Chart of Churn Rate ")
#pie(telcm$Churn)
```


```{r,results="show"}
library("ggplot2")
ggplot(data = chrun_counts, aes(x = "", y = n, fill = Churn)) + 
  geom_bar(stat = "identity") + 
  coord_polar("y")


```
```{r,results="show"}
library(ggplot2)
# Barplot
churn_plt<- ggplot(chrun_counts, aes(x="", y=n, fill=Churn))+
geom_bar(width = 1, stat = "identity")+ ggtitle("Churn Rate") +
  xlab("Total Records") + ylab("Rows Counts")
churn_plt

```

```{r,results="show"}
feat_typ_counts <- data.frame(read.csv("Feat_type_counts.csv"))
#install.packages("plotrix")
library(plotrix)

library("ggplot2")
#pie(feat_typ_counts$Counts, feat_typ_counts$Variable.Type)

piepercent<- round(100 * feat_typ_counts$Counts / sum(feat_typ_counts$Counts), 1)


feat_typ_counts$fraction <- feat_typ_counts$Counts / sum(feat_typ_counts$Counts)

# Compute the cumulative percentages (top of each rectangle)
feat_typ_counts$ymax <- cumsum(feat_typ_counts$fraction)

# Compute the bottom of each rectangle
feat_typ_counts$ymin <- c(0, head(feat_typ_counts$ymax, n=-1))

# Compute label position
feat_typ_counts$labelPosition <- (feat_typ_counts$ymax + feat_typ_counts$ymin) / 2

# Compute a good label
feat_typ_counts$label <- paste0(feat_typ_counts$Variable.Type, "\n Count: ", feat_typ_counts$Counts)


ggplot(feat_typ_counts, aes(ymax=ymax, ymin=ymin, xmax=4, xmin=3, fill=Variable.Type)) +
  geom_rect() +
  geom_label( x=3.5, aes(y=labelPosition, label=label), size=2) +
  scale_fill_brewer(palette=4) +
  coord_polar(theta="y") +
  xlim(c(2, 4)) +
  theme_void() +
  theme(legend.position = "none")






```

```{r,results="show"}


xkablesummary(telcm)

```

```{r,results="show"}
boxplot(telcm$MonthlyMinutes,
main = "Monthly Minutes of Customers",
xlab = "Monthly Min",
ylab = "Ozone",
col = "orange",
border = "brown",
horizontal = TRUE,
notch = TRUE
)


```